baseURL: "https://robdyke.com/"
title: this is rob dyke dot com
paginate: 10
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: rob dyke dot com
  description: "this is rob dyke dot com"
  keywords: [Blog]
  author: "Rob Dyke"
  # author: ["Me", "You"] # multiple authors
  images: ["rdprofile.jpg"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    # favicon: "favicon.ico"
    # favicon16x16: "favicon-16x16.png"
    # favicon32x32: "favicon-32x32.png"
    # apple_touch_icon: "apple-icon.png"
    # safari_pinned_tab: "apple-icon.png"

  label:
    text: "Home"
    icon: logo.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: rob dyke dot com
    subtitle: 
    imageUrl: "rdprofile.jpg"
    imageWidth: 150
    imageHeight: 150
    imageTitle: rob dyke dot com
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "this is rob dyke dot com 🐧"
    Content: 

  socialIcons:
    - name: twitter
      url: "https://twitter.com/robdykedotcom"
    - name: linkedin
      url: "https://linkedin.com/in/RobDyke"
    - name: keybase
      url: "https://keybase.io/robdyke"
    - name: github
      url: "https://github.com/robdyke"
    - name: gitlab
      url: "https://gitlab.com/robdyke"
    - name: bitbucket
      url:  "https://bitbucket.com/robdykedotcom"
    - name: soundcloud
      url:  "https://soundcloud.com/evilrob"
    - name: kofi
      url: "https://ko-fi.com/robdyke"
    

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    URL: "https://github.com/robdyke/h2r2d2/blob/master/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: about
      url: /about/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: search
      name: search
      url: /search/
      weight: 30
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
